### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Astelyas** [KillerDucks/csgoStats#1]
Hello @KillerDucks ,

I'm building a website about games and i would like to include some CSGO stats of my players. I know that i can do it with the Steam API, but i don't really understand how does it work... So i'm looking for something like you have. But my question is: How does your program works ?

( sorry for my english, i'm french )

Astelyas,

**Comment by Astelyas** [comment]
@KillerDucks

**Comment by KillerDucks** [comment]
Hi @Astelyas,
My Steam Web API wrapper works by you inputting a players Steam ID or use the players VanityURL.
```js
const csgoStatsNode = require('csgostatsnode'); // This will Pull in the library
const csStats = new csgoStatsNode(); //This creates a new instance of the library
```

Now you can pull the csgo Data, for example let use my Steam account all you have to do is:
```js
csStats.whatIsMyKD('76561198138999275', function(data){
   console.log("Your K/D is: " + data); //This will take the Callback data and put the output in a console log
})
```
The output will look like this:
```
Your K/D is: 0.91
```

**Comment by KillerDucks** [comment]
@Astelyas If you do not respond in the next 24 hours this issue will be locked and be marked as resolved

**Comment by Sflashy** [comment]
hey i'm getting error like this ;

`    if(opts['quiet'] == 1){

TypeError: Cannot read property 'quiet' of undefined`

**Comment by KillerDucks** [comment]
Hi @Sflashy,
First off I have updated the library so you should run
```
npm update csgostatsnode
```

also how are you setting the quiet option when you init the class it should be as follows

```js
const csgoStatsNode = require('csgostatsnode');
const csStats = new csgoStatsNode({"quiet":"1", "vanity":"true", "apikey":"<Put your api key here>"});
```
You should be using the JSON format.

**Comment by Sflashy** [comment]
thank you so much

**Comment by KillerDucks** [comment]
@Sflashy, no problem I would really appreciate if you star this repo. 😄
