### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Astelyas** [KillerDucks/csgoStats#2]
Hey it's me again !

Sorry for didn't responding for the other message... i didn't see

For now, i need your help for the instalation: you said into the "ReadMe" file that i have to run a command file but how should i do this ? by create a run.bat with this on it ?

npm install --save csgostatsnode

And how integrate your script into my website ?

**Comment by KillerDucks** [comment]
Hi,
No Problem and to run this command you need nodeJS installed with npm
> You can download it from here https://nodejs.org/en/

after that you can run this command straight from the command line, let me know when you have done this so i can continue to assist you.

**Comment by KillerDucks** [comment]
@Astelyas

**Comment by Astelyas** [comment]
Okay, i'll try it when i'll at home

**Comment by Astelyas** [comment]
I downloaded the software but about the installation, i guess i have to instal it on my web server... But i don't know how to do that... :/

**Comment by KillerDucks** [comment]
@Astelyas,
Follow the instructions on the web site it gives you a full guide on setting it up.

**Comment by Astelyas** [comment]
I found some instructions... but i'm a newbie on this so i don't know how to do that... It will take me a lot of time to find how to instal nodeJS on my website, but i'll tell you when i'll finish

**Comment by Astelyas** [comment]
OK i found maybe.... a issues... but i have to buy another webserver in another web hosting in order to use the SSH option... :/

**Comment by KillerDucks** [comment]
@Astelyas,
You can test this out on your computer first and then decide if you need to buy a new webserver/vps

**Comment by Astelyas** [comment]
Actually i'm on a test webserver ( free ) so i have to buy a real webserver in any case

**Comment by KillerDucks** [comment]
@Astelyas, 
Please respond in 24 hours or this issue will be closed and set to resolved.
Thanks.

**Comment by Astelyas** [comment]
I close this issue, and i'll open a new one when i'll get my webserver
