### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by Astelyas** [KillerDucks/csgoStats#3]
Hi! 

I recieved my webserver but i asked to the support how to instal sofware like NodeJS and they said that NodeJS doesn't work on their webserver 

Is there an other method to instal NodeJS ?

**Comment by KillerDucks** [comment]
Hi @Astelyas,
Unfortunately there is not another way to install nodeJS.
Also note you need a VPS and not just a web server, a web server does not contain npm or node but has things like apache, php and ruby just to name a few.
